#!/bin/bash
WALLPAPER_DIR="~/Wallpapers"

if [ ! -d "$WALLPAPER_DIR" ]; then
    echo "Папка $WALLPAPER_DIR не найдена!"
    exit 1
fi
RANDOM_WALLPAPER=$(find "$WALLPAPER_DIR" -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" \) | shuf -n 1)

if [ -n "$RANDOM_WALLPAPER" ]; then
    pkill swaybg
    swaybg -i "$RANDOM_WALLPAPER" -m fill &
fi